// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// survLm_fit
List survLm_fit(arma::colvec y, arma::mat X, arma::colvec weights);
RcppExport SEXP rpms_survLm_fit(SEXP ySEXP, SEXP XSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(survLm_fit(y, X, weights));
    return rcpp_result_gen;
END_RCPP
}
// survLm_model
List survLm_model(arma::colvec y, arma::mat X, arma::colvec weights, arma::ivec strata, arma::ivec clusters);
RcppExport SEXP rpms_survLm_model(SEXP ySEXP, SEXP XSEXP, SEXP weightsSEXP, SEXP strataSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(survLm_model(y, X, weights, strata, clusters));
    return rcpp_result_gen;
END_RCPP
}
// get_loss
arma::vec get_loss(arma::vec x_val, arma::colvec y, arma::mat mX, arma::colvec weights, double M);
RcppExport SEXP rpms_get_loss(SEXP x_valSEXP, SEXP ySEXP, SEXP mXSEXP, SEXP weightsSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x_val(x_valSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(get_loss(x_val, y, mX, weights, M));
    return rcpp_result_gen;
END_RCPP
}
// get_loss_cat
arma::vec get_loss_cat(arma::mat sets, arma::vec cats, arma::vec x_val, arma::colvec y, arma::mat mX, arma::colvec weights, double M);
RcppExport SEXP rpms_get_loss_cat(SEXP setsSEXP, SEXP catsSEXP, SEXP x_valSEXP, SEXP ySEXP, SEXP mXSEXP, SEXP weightsSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sets(setsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type cats(catsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_val(x_valSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(get_loss_cat(sets, cats, x_val, y, mX, weights, M));
    return rcpp_result_gen;
END_RCPP
}
// clus_perm
arma::mat clus_perm(arma::vec y, arma::vec weights, arma::uvec clus, arma::uword M);
RcppExport SEXP rpms_clus_perm(SEXP ySEXP, SEXP weightsSEXP, SEXP clusSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type clus(clusSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(clus_perm(y, weights, clus, M));
    return rcpp_result_gen;
END_RCPP
}
// var_test
List var_test(arma::mat p_scores, arma::mat mX, arma::vec var, int cat);
RcppExport SEXP rpms_var_test(SEXP p_scoresSEXP, SEXP mXSEXP, SEXP varSEXP, SEXP catSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type p_scores(p_scoresSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type var(varSEXP);
    Rcpp::traits::input_parameter< int >::type cat(catSEXP);
    rcpp_result_gen = Rcpp::wrap(var_test(p_scores, mX, var, cat));
    return rcpp_result_gen;
END_RCPP
}
// get_pvec
List get_pvec(arma::mat p_scores, arma::mat mX, arma::mat vars, arma::ivec cat_vec);
RcppExport SEXP rpms_get_pvec(SEXP p_scoresSEXP, SEXP mXSEXP, SEXP varsSEXP, SEXP cat_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type p_scores(p_scoresSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type cat_vec(cat_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pvec(p_scores, mX, vars, cat_vec));
    return rcpp_result_gen;
END_RCPP
}
