# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

survLm_fit <- function(y, X, weights) {
    .Call('rpms_survLm_fit', PACKAGE = 'rpms', y, X, weights)
}

#' Fit a linear model using data collected from a complex sample
#' 
#' @param y A vector of values
#' @param X The design matrix of the linear model  
#' @param weights A vector of sample weights for each observation 
#' @param strata A vector of strata labels
#' @param clusters A vector of cluster labels
#' 
#' @return list containing coefficients, covariance matrix and the residuals
#' 
survLm_model <- function(y, X, weights, strata, clusters) {
    .Call('rpms_survLm_model', PACKAGE = 'rpms', y, X, weights, strata, clusters)
}

get_loss <- function(x_val, y, mX, weights, M) {
    .Call('rpms_get_loss', PACKAGE = 'rpms', x_val, y, mX, weights, M)
}

get_loss_cat <- function(sets, cats, x_val, y, mX, weights, M) {
    .Call('rpms_get_loss_cat', PACKAGE = 'rpms', sets, cats, x_val, y, mX, weights, M)
}

clus_perm <- function(y, weights, clus, M) {
    .Call('rpms_clus_perm', PACKAGE = 'rpms', y, weights, clus, M)
}

var_test <- function(p_scores, mX, var, cat) {
    .Call('rpms_var_test', PACKAGE = 'rpms', p_scores, mX, var, cat)
}

get_pvec <- function(p_scores, mX, vars, cat_vec) {
    .Call('rpms_get_pvec', PACKAGE = 'rpms', p_scores, mX, vars, cat_vec)
}

