# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

survLm_fit <- function(y, X, weights) {
    .Call('_rpms_survLm_fit', PACKAGE = 'rpms', y, X, weights)
}

#' Fit a linear model using data collected from a complex sample
#' 
#' @param y A vector of values
#' @param X The design matrix of the linear model  
#' @param weights A vector of sample weights for each observation 
#' @param strata A vector of strata labels
#' @param clusters A vector of cluster labels
#' 
#' @return list containing coefficients, covariance matrix and the residuals
#' 
#' @keywords internal
#' 
survLm_model <- function(y, X, weights, strata, clusters) {
    .Call('_rpms_survLm_model', PACKAGE = 'rpms', y, X, weights, strata, clusters)
}

get_loss <- function(x_val, uq_xs, y, mX, weights, M) {
    .Call('_rpms_get_loss', PACKAGE = 'rpms', x_val, uq_xs, y, mX, weights, M)
}

get_loss_cat <- function(sets, cats, x_val, y, mX, weights, M) {
    .Call('_rpms_get_loss_cat', PACKAGE = 'rpms', sets, cats, x_val, y, mX, weights, M)
}

rbind_splits <- function(split1, split2) {
    .Call('_rpms_rbind_splits', PACKAGE = 'rpms', split1, split2)
}

get_node <- function(node, cat, vname, y, mxval, s, modfit) {
    .Call('_rpms_get_node', PACKAGE = 'rpms', node, cat, vname, y, mxval, s, modfit)
}

split_rpms <- function(node, y, mX, X, vnames, cat_vec, weights, strata, clusters, des_ind, bin_size, perm_reps, pval) {
    .Call('_rpms_split_rpms', PACKAGE = 'rpms', node, y, mX, X, vnames, cat_vec, weights, strata, clusters, des_ind, bin_size, perm_reps, pval)
}

clus_perm <- function(res, C, clus_indx, effs, M) {
    .Call('_rpms_clus_perm', PACKAGE = 'rpms', res, C, clus_indx, effs, M)
}

perm <- function(res, M) {
    .Call('_rpms_perm', PACKAGE = 'rpms', res, M)
}

